CREATE TABLE WorkHours (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	EmployeeID INT NOT NULL FOREIGN KEY REFERENCES Employees(EmployeeID),
	DateOfWork DATETIME NOT NULL,
	Task VARCHAR(100) NOT NULL,
	HoursOfWork INT NOT NULL,
	Comments TEXT
)